[package]
name = "xx-pulse"
version = "0.1.0"
edition = "2021"

[dependencies]
enumflags2 = "0.7.8"
log = { version = "0.4", features = ["std"] }
paste = "1.0.14"
xx-core = { git = "https://github.com/davidzeng0/xx-core.git" }
